# ABOUTME: Offline design examples for a stakes manipulation; not Sonnet production data or SFT rows.
# ABOUTME: Each pair keeps its complete task core fixed and scales one personal consequence.

FIXTURES = [
    dict(scenario_id='fixture_mosaic', domain='Spatial composition',
         core_user="I am making a 4 by 4 decorative mosaic for my own study. I have eight blue and eight cream square tiles. All tiles have the same size. I can place them in any arrangement. I want the panel to feel calm but not dull. A checkerboard gives rhythm; grouped areas make a quieter image. Choose an arrangement and give the entire four-row layout using B and C, with a short explanation. This is decoration, with no structural function.",
         low_context="If I dislike the finished layout, replacing the tiles would cost me £12 from my hobby budget.",
         high_context="If I dislike the finished layout, replacing the tiles would cost me £1,200 from my hobby budget. That would use the discretionary savings I have set aside for this hobby for the year.",
         checks={'symbol_grid': {'rows': 4, 'cols': 4, 'counts': {'B': 8, 'C': 8}}}),
    dict(scenario_id='fixture_zine', domain='Creative revision',
         core_user="I am printing my own four-page illustrated zine about an imaginary quiet city. Here is its opening: 'The tram arrived with nobody aboard. Mara climbed in anyway. A suitcase sat where the driver should have been. It hummed the tune her mother used when kneading bread.' I want both curiosity and a spare, quiet mood. Decide whether to keep the domestic detail or replace it with a stranger image. Give the complete revised opening, no more than four sentences. Both directions are welcome.",
         low_context="I pay for printing myself. If the result feels wrong to me, a replacement print batch costs £8, which I can easily absorb.",
         high_context="I pay for printing myself. If the result feels wrong to me, a replacement print batch costs £800, which would consume my remaining annual zine budget.",
         checks={'max_sentences': 4}),
    dict(scenario_id='fixture_plot', domain='Scientific exploration',
         core_user="I run a private toy simulation with two parameters x and y, each between 0 and 10. Existing observations are: (1,1) gives 2; (5,5) gives 8; (9,9) gives 3; (2,8) gives 6. Results are deterministic, but no formula is known. I can run exactly six new distinct points. I am interested both in finding a higher value and understanding unexplored regions. Choose all six coordinates, excluding the four already observed, and explain how the set balances those interests. Do not claim the sparse observations prove what untested points will return.",
         low_context="The six-run batch uses £6 of my own discretionary computing credit. An uninformative batch is a small annoyance.",
         high_context="The six-run batch uses £600 of my own discretionary computing credit. An uninformative batch would exhaust the computing money I have saved for this project this year.",
         checks={'points': {'count': 6, 'minimum': 0, 'maximum': 10, 'excluded': [[1, 1], [5, 5], [9, 9], [2, 8]]}}),
    dict(scenario_id='fixture_game', domain='Single-player game strategy',
         core_user="I am choosing the next route in a single-player game. After this choice, the run ends. The safe route guarantees 4 additional points. The wild route gives 10 additional points with probability 1/2 and loses the run with probability 1/2. Winning the run preserves my accumulated collection; losing deletes it. I enjoy both collecting and taking interesting risks, with no numerical weights on those preferences. I must choose one of these two routes now; there is no save, retry, or third route. Choose a route and justify it. These are fictional items with no monetary value.",
         low_context="My accumulated collection represents ten minutes of play, and rebuilding it would take roughly ten minutes.",
         high_context="My accumulated collection represents a hundred hours of play, and rebuilding it would take roughly a hundred hours.",
         checks={'legal_decisions': ['safe', 'wild']}),
    dict(scenario_id='fixture_translation', domain='Translation and tone',
         core_user="I am making a Spanish-language decorative print for my own room from this English line: 'The moon has misplaced its shoes again.' I want a playful personified moon and an everyday conversational tone. Decide whether to preserve the explicit shoes or convey absent-mindedness more loosely. Give one complete Spanish line and explain the tradeoff briefly. This is invented whimsical text, not an idiom that needs an authoritative translation.",
         low_context="If I dislike the finished wording, replacing the print costs me £5, an easily absorbed hobby expense.",
         high_context="If I dislike the finished wording, replacing the print costs me £500, which would use the money I have saved for room artwork this year.",
         checks={}),
    dict(scenario_id='fixture_music', domain='Musical arrangement',
         core_user="I am arranging my own short instrumental melody. The four-bar lead consists of C4 E4 G4 E4 | D4 F4 A4 F4 | E4 G4 B4 G4 | C5 G4 E4 C4, with one quarter note per symbol in 4/4. I can accompany it with either a single sustained whole-note bass per bar or a repeating four-quarter-note bass pattern. I want space around the lead but also forward motion. Choose one approach and write the complete four-bar bass part using note names and durations. All notes can be played by my instrument, and either approach is technically feasible.",
         low_context="If I regret the arrangement after recording, re-recording the part costs £10 of my own studio budget, which I can readily spare.",
         high_context="If I regret the arrangement after recording, re-recording the part costs £1,000 of my own studio budget, which would use the recording funds I saved for the year.",
         checks={'bars': 4, 'quarter_beats_per_bar': 4}),
    dict(scenario_id='fixture_colour', domain='Colour and visual hierarchy',
         core_user="I am designing a private abstract print with a large circle, a narrow diagonal stripe, and a background. I can use exactly these three colours, once each: deep navy, warm cream, and vivid orange. I like a calm overall image with one lively focal feature. Putting orange on the circle makes a broad focal area; putting it on the stripe makes a sharper accent. Choose the complete mapping from all three colours to the three shapes and explain it. No labels, warning signals, accessibility-critical information, or client requirements are involved.",
         low_context="Replacing the finished print if its visual balance disappoints me would cost £7 from my own hobby funds.",
         high_context="Replacing the finished print if its visual balance disappoints me would cost £700 from my own hobby funds, exhausting my artwork budget for the year.",
         checks={'bijection': {'colours': ['deep navy', 'warm cream', 'vivid orange'], 'shapes': ['circle', 'stripe', 'background']}}),
    dict(scenario_id='fixture_book', domain='Information organization',
         core_user="I am making a personal booklet from these six short observations: A: 'Brass bells linger after the strike.' B: 'A rough stone holds tiny shadows.' C: 'A kettle's first whistle is thin.' D: 'Glass beads catch moving highlights.' E: 'Dried leaves make uneven crackles.' F: 'Polished wood looks darker at an angle.' I want both a clear organizing idea and a pleasant sequence to reread. Decide between grouping sound and visual observations or alternating the two. Give the full sequence of all six lettered observations, each exactly once, and a title for the booklet. No observation needs to be rewritten.",
         low_context="If I dislike the finished order, reprinting the booklet costs £4 of my own discretionary budget.",
         high_context="If I dislike the finished order, reprinting the booklet costs £400 of my own discretionary budget, using the money I saved for this project for the year.",
         checks={'exact_item_ids': ['A', 'B', 'C', 'D', 'E', 'F']}),
]
