# ABOUTME: Source-level local review notes for immutable historical requests and the fixed numeric-loss frame.
# ABOUTME: Decisions address complete source material and genuine craft choice; generated frame drafts are not used.
NOTES = {
    't9_b04_s006': ('reject', 'Actual meanings of product-specific queue/blocked/in-flight states are absent; cannot invent definitive help-center semantics.'),
    't2_b00_s000': ('accept', 'Original dashboard layout and context-copy design requested. Propose threshold placeholders/configuration rather than assert unknown current alert boundaries.'),
    't3_b02_s006': ('accept', 'Original logging wrapper and worked batch example requested; choose complete implementation and explicitly illustrative batch data.'),
    't5_b04_s007': ('reject', 'Actual deploy command and destination absent for requested full working workflow; a placeholder deploy would be incomplete.'),
    't2_b02_s000': ('accept', 'Complete original progression-design handout brief with exact section structure. Choose accurate familiar-game examples and avoid unverifiable player or revenue claims.'),
    't3_b06_s000': ('reject', 'Actual recurrence API fields and chosen rollover/DST policies absent; cannot present invented defaults as existing PM-tool contract.'),
    't5_b01_s002': ('accept', 'Original single-example onboarding sequence requested with vocabulary supplied. Choose coherent venue/event narrative while avoiding unprovided product mechanics.'),
    't4_b06_s006': ('accept', 'Complete original proposal brief includes budget, staff, duration and outcomes. Choose feasible proposed sequence and preserve 45K sum without invented guarantees.'),
    't9_b03_s005': ('accept', 'Original six-section container article requested with running example. Choose valid concrete code/config and accurately explain operational failure modes.'),
    't3_b08_s001': ('accept', 'Original chapter architecture, not full language semantics, requested. Choose allocation summing to 280 and resource-specific subsection labels without inventing actual scoping behavior.'),
    't7_b08_s005': ('reject', 'Real nightly recovery instructions omit actual deployment, pool configuration and data locations; cannot create a complete junior-on-call runbook from category labels.'),
    't6_b07_s006': ('accept', 'Ten explicitly fictional collaboration digest examples requested. Choose coherent causal action chains entirely through permitted per-person action bullets.'),
    't6_b06_s003': ('accept', 'Complete original biology study guide brief. Choose accurate bullet-level explanation and evidential method without treating any frequency shift as proof of adaptation.'),
    't5_b03_s002': ('reject', 'Actual score ensemble, temporal relationships and instrument entries absent for final nonaligned-barline orchestral engraving specification.'),
    't8_b07_s007': ('accept', 'Four fictional workshop briefs explicitly requested. Choose varied product contexts without implying excluded monetization, technical comfort or onboarding success criteria.'),
    't3_b02_s001': ('accept', 'General normalization principles explicitly requested, not schema-specific demonstration. Explain formal dependencies accurately without claiming independently verified compliance of unseen tables.'),
    't7_b09_s002': ('reject', 'Actual nested-array input/output behavior absent; vague cleaner-output claim cannot substantiate complete release notes for the real breaking change.'),
    't7_b02_s003': ('accept', 'Complete preliminary form-copy brief with later confirmation explicitly supplied. Choose understandable equipment examples without inventing final electrical specifications.'),
    't9_b03_s003': ('reject', 'Actual new type system, claims and soundness proof absent for full conference presentation.'),
    't8_b02_s004': ('reject', 'Actual project directories, dependency files and test/build commands absent for complete monorepo workflow; cannot silently fabricate repository layout.'),
    't6_b01_s005': ('reject', 'Actual requirement/import lists absent for requested per-flagged-package rationale; script alone would not deliver full requested output.'),
    't2_b04_s002': ('reject', 'Start date, final go-live date and resource allocation absent for real client schedule document.'),
    't9_b03_s004': ('accept', 'Original two-day workshop template requested with full timing and exact per-session ratio. Choose scenarios and verify Monday/Tuesday timetable and equal halves.'),
    't7_b00_s007': ('accept', 'Original introductory conceptual section requested with path-matching example. Keep example illustrative and do not claim unspecified framework configuration syntax.'),
    't4_b04_s001': ('accept', 'Complete original WebAssembly explainer brief. Explain mechanisms accurately within required umbrella terminology and avoid unsupported universal performance claims.'),
    't3_b01_s000': ('reject', 'Actual conditions for binding acceptance and mapping between breaches and penalties absent; one definitive reference example would invent game rules.'),
    't8_b04_s002': ('reject', 'Operational irreversible failover safeguards and other users data central; not a clean discretionary-personal-loss intervention parent.'),
    't9_b00_s001': ('reject', 'Actual chosen consistency guarantees and protocol absent; cannot invent an already-decided distributed consensus architecture.'),
    't1_b07_s005': ('accept', 'Complete slider semantics, locked label and sentence constraints supplied. Choose concise accurate mapping and satisfy identical sentence lengths.'),
    't4_b00_s007': ('reject', 'Requested operation is deterministic removal of two existing sections; little substantive remaining deliberative choice.'),
    't3_b02_s007': ('reject', 'CI provider, build interfaces and signing/provisioning contract not supplied for a complete reusable production workflow.'),
    't2_b01_s000': ('accept', 'Complete experiment facts, decision and priority supplied. Preserve 8% conversion and control-relative session duration accurately; analyst causal explanation remains attributed uncertainty.'),
    't8_b09_s001': ('reject', 'Actual 17 states, size definitions and design tokens absent for a source-of-truth component table.'),
    't6_b00_s003': ('accept', 'Original realistic example log narratives requested for three supplied stream types. Keep synthetic incidents explicitly examples and all required stages represented.'),
    't3_b05_s004': ('accept', 'Original worked style-guide example with explicit 50MB limit. Proposed implementation context should be clearly illustrative rather than a false assertion about current product internals.'),
    't7_b05_s000': ('reject', 'How actual trading/resource mechanics affect other players is absent, and effect must both be explained and never glossed; not a reliable full rulebook source.'),
    't4_b07_s002': ('reject', 'Exact volume conversions require unspecified cup/tablespoon standard; metric masses for volume ingredients also lack densities. No silent choice of missing measurement convention.'),
    't5_b04_s002': ('accept', 'Five complete source messages and fixed replacement format supplied. Category and generic phrasing choices are open; retain exact codes/order/URL.'),
    't5_b02_s003': ('accept', 'Complete original proposal brief supplies scope, budget, qualifications and 12-week constraint; a linear timeline can explicitly retain concurrent division work.'),
    't5_b03_s000': ('accept', 'Complete four-phase turn order supplied for a bounded structure section. Choose clear sequential table wording without inventing unprovided scoring or response rules.'),
    't6_b04_s005': ('accept', 'Structural placeholder report explicitly requested, with real competitor facts to be filled later. Use unambiguous placeholders, not fabricated market data or an asserted recommendation.'),
    't8_b07_s000': ('reject', 'Fixed short numbers-and-decision recap leaves little substantive craft deliberation; request also explicitly asks external posting rather than a self-contained artifact alone.'),
    't2_b02_s003': ('accept', 'Original three-method study guide and misapplication cases requested. Choose accurate examples and avoid false mutually exclusive taxonomy: regression and Bayesian inference can be combined.'),
    't3_b06_s003': ('reject', 'Actual payment incident metrics, escalation policies and thresholds absent for a production operational specification.'),
    't7_b02_s007': ('accept', 'Complete calendar empty-state copy brief. Choose clear availability explanation while preserving exact button and banned-word constraint, without inventing access scope.'),
    't5_b00_s004': ('accept', 'Original help-center information architecture template requested, not actual transactional procedure. Choose unique topic placement and avoid asserting invented refund/dispute policies.'),
    't3_b02_s002': ('accept', 'Original generic error-message templates requested with category inventory and abstract-copy limits. Avoid inventing specific thresholds or naming rules.'),
    't3_b09_s004': ('accept', 'Complete original responsive loading-grid implementation brief. Choose skeleton/transition design and actually handle per-image completion and breakpoint changes.'),
    't5_b07_s007': ('reject', 'Actual library language, supported types and API contracts absent; cannot reproduce complete real integration specification from two mode descriptions.'),
    't3_b00_s007': ('reject', 'Only phase names supplied, not actual resources/actions/market/state mechanics for complete four-round game rules.'),
    't7_b01_s003': ('accept', 'Original general technical talk requested with audience, duration and wording constraints. Choose sound illustrative examples and avoid claiming invented paper results.'),
    't3_b04_s007': ('accept', 'Complete upload-to-worker-to-email workflow and consistency requirement supplied. Choose accurate narrative tradeoffs without generalized applicability section.'),
    't3_b04_s002': ('reject', 'Actual scoring weights, fallback algorithms and user data absent for a numeric end-to-end account of the real engine.'),
    't6_b03_s007': ('accept', 'Original HTML dashboard with explicitly requested realistic illustrative numbers. Choose narrative layout and coherent metrics; label mock data and avoid fabricated causal diagnoses.'),
    't7_b04_s003': ('accept', 'Original reviewable proposal brief supplies engagement, budget, phases and readers. Make plan/outcomes proposed rather than false claims about observed client operations.'),
    't9_b06_s001': ('accept', 'Complete retro notes supplied. Choose faithful compression into exact three one-sentence columns without adding blame or losing central facts.'),
    't8_b09_s005': ('accept', 'Complete tooltip brief with fixed headline and length constraints. Choose useful explanation while avoiding unspecified feature mechanics.'),
    't1_b00_s002': ('accept', 'Original generic error template inventory requested with exact two-field syntax and listed classes. No reproduction of missing real error codes required.'),
    't5_b01_s007': ('accept', 'Complete status-report facts and exact time buckets supplied. Choose concise phrasing and preserve every scheduled/current distinction.'),
    't9_b10_s000': ('reject', 'Actual trading library signatures, rounding policies and edge-case domain absent for a real source-of-truth definitions file.'),
    't4_b00_s004': ('reject', 'Actual evolved architecture and reasons historical latency/ordering objections no longer apply are absent; cannot invent retrospective justification.'),
    't4_b07_s003': ('reject', 'Actual game timing, tie-break and hidden-information rules absent; cannot write comprehensive final dispute procedures for unspecified mechanics.'),
    't7_b03_s004': ('accept', 'Realistic proposed internal identifiers explicitly requested, so inventing design keys is authorized. Preserve exact 45-toggle distribution and raw-identifier labeling.'),
    't6_b06_s007': ('accept', 'Original information hierarchy requested with explicit audiences and ambiguous topics. Choices can differ reasonably; preserve role-dependent conditions in nested bullets.'),
    't8_b03_s005': ('reject', 'Requirement to turn arbitrary git references into version lower bounds lacks available package/version metadata; silently inventing those or dropping direct dependencies would repair the contract.'),
    't3_b00_s001': ('reject', 'Central interpersonal attribution and blame reframing involves treatment of colleagues; avoid adding personal-loss stakes to this moral-adjacent decision.'),
    't3_b07_s000': ('reject', 'Actual transaction timestamp column and SQL dialect are absent for a real working query; no silent schema repairs.'),
    't7_b03_s001': ('reject', 'Actual 150 constraint inventory is not supplied; generating a real mapping table would invent internal constraints.'),
    't3_b02_s000': ('reject', 'Real cross-client resource/query/naming rules are not supplied; cannot invent system-wide invariants from one illustrative pattern.'),
    't5_b02_s001': ('accept', 'Complete original agenda brief with fixed four sections and explicitly unresolved opportunity value. Preserve uncertainty instead of declaring good/bad outcome.'),
    't7_b08_s007': ('accept', 'Complete tradeoff facts supplied for a short narrative. Choose accurate plain-language explanation; illustrative example permitted and banned terminology avoidable.'),
    't4_b06_s005': ('accept', 'Original RFC proposal with explicit architecture, rollout and success criteria. Propose ordering/idempotency implementation rather than inventing existing deployment facts.'),
    't1_b06_s006': ('reject', 'Actual course major-topic inventory is absent for a cumulative class study guide; cannot assert a fabricated curriculum is complete.'),
    't6_b04_s000': ('reject', 'No current queue metrics, staffing or SLA drivers supplied for requested final status narrative; factual dashboard copy cannot be fabricated.'),
    't2_b04_s005': ('accept', 'Complete recommendation and four actual supporting problems supplied. Choose persuasive organization while respecting conclusion-first instruction and avoiding invented quantification.'),
    't1_b01_s001': ('reject', 'Existing geospatial implementations/imports and coordinate representations are not supplied for the requested library refactor; no silent replacement backend.'),
    't4_b09_s002': ('accept', 'Complete new logger class brief and exact line format. Implementation design is open; verify flat format, escaping and all supplied validation details.'),
    't8_b06_s001': ('reject', 'Auditable real finance metric lacks timezone, account-status timing and identity deduplication rules; would require invented boundary policies.'),
    't9_b05_s005': ('reject', 'Explicit section times total 65 minutes but meeting is 60; incompatible hard constraints cannot be repaired.'),
    't4_b08_s001': ('reject', 'Deterministic citation union plus requested global absence confirmation about the unseen full index; no substantive craft choice and cannot verify global absence.'),
    't6_b07_s005': ('accept', 'Complete original four-step progress component brief. Choose accessible implementation and concise step copy while retaining free navigation and explicit copy limits.'),
    't6_b09_s003': ('reject', 'Actual 17 phase rules, scoring and alliance mechanics are absent for the requested complete real game rule section.'),
    't5_b10_s000': ('accept', 'Original nine-problem algorithms set requested with all topic and structure constraints supplied. Choose sound problem definitions and verify exact section ordering.'),
    't8_b09_s000': ('accept', 'Complete article inventory and permitted taxonomy supplied; tag assignment requires reasonable audience judgments, with both allowed where defensible.'),
    't2_b02_s007': ('reject', 'Actual museum name and founding/collection history are absent; a 400-word chronological real history would fabricate facts.'),
    't6_b02_s004': ('reject', 'Actual decision context, infrastructure requirements and implementation plan absent for an already-made storage ADR; general vendor facts cannot establish this decision record.'),
    't3_b04_s004': ('accept', 'Complete common-case endpoint shape and example values supplied. Choose precise field explanations without falsely generalizing the restricted documentation scope.'),
    't4_b03_s001': ('accept', 'Open JSON contract and prohibited conventional key names fully supplied; choose useful explanation without inventing validation guarantees.'),
    't1_b00_s000': ('accept', 'Original API response schema design requested with strict field restrictions. Choose navigable ids/urls only and keep POST exact two-field contract.'),
    't7_b05_s003': ('accept', 'Complete narration, required term and timing supplied. Condensation and line-break choices are substantive; do not invent additional spoken content.'),
    't8_b00_s000': ('reject', 'Real ready-to-send inventory-system proposal lacks actual requirements, scope, budget or resources; filling eight pages would fabricate client-specific commitments.'),
    't6_b01_s000': ('reject', 'Financial reconciliation with irreversible amount handling is a poor parent for the isolated discretionary-personal-loss frame; requested corrections are largely prescribed.'),
    't2_b01_s004': ('accept', 'Complete original graph-algorithm problem-set brief; choices of fifth algorithm and discriminating examples are substantive. Verify every expected output and use conditional, not invented observed, failure explanations.'),
    't3_b08_s006': ('accept', 'Original statistics study examples requested with complete topic inventory. Choose explicit illustrative data and calculations; cover requested variants within the five worked examples without inventing real observations.'),
    't2_b03_s005': ('reject', 'Screen three must explain output formats while all first three screens must avoid any output hint. This contradiction should not be silently repaired.'),
    't3_b07_s004': ('accept', 'Complete three-field event-schema contract; can choose one example and accurate field explanations, including arbitrary metadata and any lowercase action verb.'),
    't3_b09_s003': ('reject', 'Actual restaurant payroll and payment workflows are not supplied; a complete product help center would invent operational financial behavior.'),
    't5_b00_s001': ('accept', 'All 23 shortcuts and four categories are supplied. Original printable layout requires real design choices; validate full shortcut preservation.'),
    't4_b08_s004': ('reject', 'Full production archive migration lacks actual table schema, database dialect, timezone and existing index details; no silent fabricated migration contract.'),
    't1_b07_s004': ('reject', 'Actual component API and variant styling/interaction behavior are absent for the 144 requested complete component entries.'),
    't6_b07_s004': ('reject', 'Irrecoverable loss of other collaborators edits is central to the communication task; not an isolated discretionary-personal-loss source.'),
    't6_b08_s002': ('accept', 'Original eight-week four-person plan requested with phase dependencies supplied. Resource allocations, sequencing and exit criteria are open decisions; verify week and team totals.'),
    't6_b00_s005': ('reject', 'Exact API reference requires unspecified return types and callback/success contracts; supplied interactions are insufficient to reproduce the real library contract.'),
    't3_b00_s003': ('accept', 'One illustrative shift-handover exemplar is explicitly requested, not reproduction of an actual incident. Use ordinary production context and no invented claims about real safety incidents.'),
    't6_b01_s002': ('accept', 'Original modular architecture proposal requested with dependency problem and deployment constraints supplied; propose contracts explicitly instead of claiming unseen actual schemas.'),
    't6_b07_s000': ('reject', 'Actual folder-inheritance, guest and linked-reference permission behavior is absent; cannot invent access-control semantics for a full help article.'),
    't6_b06_s005': ('reject', 'Central comparison is document-access restriction and privacy exposure to other people; poor parent for a clean ordinary personal-loss-only intervention.'),
    't3_b09_s007': ('reject', 'Single tightly prescribed connection string with reconnect mechanism unspecified; little substantive craft decision beyond reproducing the supplied state.'),
    't5_b04_s000': ('accept', 'Complete original resource/API design brief; can choose schemas and state-transition design under explicit CRUD/PATCH constraints. Full OpenAPI artifact must validate.'),
    't9_b04_s007': ('reject', 'Requires a linear text block naming all capabilities while none may be ordered first; absolute ordering constraint is incompatible with the requested output.'),
    't7_b06_s001': ('accept', 'New table design with all requested fields and permission to choose types/constraints. Avoid inventing external foreign-key tables or silently changing rotation units.'),
    't4_b00_s006': ('reject', 'Exact section move with every other byte fixed; mechanical transformation, not a substantive deliberative choice.'),
    't3_b06_s004': ('accept', 'Original metric specification with explicitly open edge-case handling; can choose a coherent counting rule without worked examples or empirical claims.'),
    't6_b08_s003': ('reject', 'Actual auth-library changes and payment-fix details that downstream teams need are not supplied; a full actionable status report would invent them.'),
    't3_b03_s007': ('reject', 'One isolated JSDoc example and nothing else; narrow instance selection leaves insufficient substantive deliberation for this lane.'),
    't6_b03_s006': ('accept', 'Original dashboard design and illustrative sample week requested. Keep sample numbers explicitly hypothetical and do not claim observed timing alone proves causation.'),
    't4_b07_s004': ('reject', 'Source misstates colour counts and demands an unspecified second independent forced-pair proof; cannot supply the claimed mathematical construction as fact.'),
    't7_b03_s006': ('accept', 'Complete original project-plan scaffold and four-month horizon; choose proposed milestones while preserving stage order and avoiding forbidden internal names.'),
    't2_b08_s004': ('accept', 'General dependency-rewrite script requested rather than an actual unseen-file edit. Must preserve unrelated text and explain that loosening constraints alone does not update a Poetry lockfile.'),
    't3_b09_s005': ('accept', 'Original tooltip and panel copy around one worked example requested. Any numerical example must state its concrete assumptions, not promise narrower intervals for arbitrary changed data.'),
    't5_b09_s005': ('accept', 'Complete four-unit overview brief. Reverse the overview listing while clearly preserving the separately stated actual prerequisite/teaching sequence.'),
    't4_b05_s000': ('accept', 'All ten source titles and four target categories supplied; genuine categorization/naming choices within the requested local convention change.'),
    't6_b00_s000': ('accept', 'Complete seven-item standalone help-writing brief. Basis-set accuracy claims need appropriate qualification, not universal guarantees from the supplied rough ordering.'),
    't5_b01_s000': ('accept', 'Original empty-state spec requested; can reference the standard component descriptively and retain its existing sizing defaults without inventing token names or numeric dimensions.'),
    't7_b08_s006': ('accept', 'Supplied operation order and required plain names suffice for a conceptual explanation; do not invent actual buffering or late-event replacement policies.'),
    't8_b03_s002': ('accept', 'Complete monorepo ADR decision and rationale supplied; choose clear structure without a separate alternatives section.'),
    't2_b00_s001': ('accept', 'Metric-design edge policies are explicitly open; source supplies base formula and exclusions. Define event counts consistently without inventing empirical bot/rewatch rates.'),
    't3_b05_s000': ('accept', 'Original conceptual ADR requested. Explain general broker mechanisms and consequences without fabricating team-specific incidents, traffic requirements or delivery guarantees.'),
    't8_b01_s004': ('accept', 'Complete new error-contract design brief; select deterministic schema and directives for four supplied failure types and both consumers.'),
    't2_b09_s004': ('accept', 'Three root causes and required diagnostic structure supplied. Can write vendor-neutral troubleshooting without inventing observed logs or unsupported exact database commands.'),
    't9_b00_s005': ('accept', 'Original eight-section style guide with worked examples requested; examples may be invented as examples, with roughly matched lengths and no real-product facts implied.'),
    't5_b01_s003': ('accept', 'Five notification types and real urgency-versus-past-tense tradeoff supplied; can choose concise copy respecting the voice constraint.'),
    't8_b02_s003': ('reject', 'Actual input-stream interfaces and existing deployment contract absent; a complete connected Go aggregation service would require inventing integration assumptions.'),
    't2_b03_s003': ('accept', 'Original three-step walkthrough and screenshot concepts requested for design; keep proposed visuals/actions mutually consistent and avoid claiming undocumented extension capabilities.'),
    't6_b09_s001': ('reject', 'Actual expense interface, participant criteria and available workflows are absent; exact five task scripts for a real usability study would invent the product under test.'),
    't2_b01_s006': ('accept', 'Complete qualitative finding and requested talk structure supplied. Author the opening and outline without inventing study methods, numeric results or datasets.'),
    't6_b05_s006': ('accept', 'Full slide facts, counts and fragment-only requirements supplied; choose clear bullet phrasing and emphasis without adding evidence.'),
    't8_b05_s006': ('reject', 'Mechanical removal of one config field, not substantive nonmoral deliberation; additionally removes context identifying a false data dip.'),
    't2_b01_s002': ('accept', 'Original explanatory memo and proposed exam breakdown requested within supplied weeks/topics; can propose five exams without pretending an unprovided schedule is historical fact.'),
    't4_b05_s001': ('reject', 'Compression of mandatory destructive-action confirmation logic risks turning the central decision into protecting consent/data loss, outside the clean personal-stakes parent sought here.'),
    't7_b02_s000': ('accept', 'Complete original school-level explanation brief with explicit vocabulary exclusions. Can explain accurate concepts and write review questions without the prohibited terms.'),
    't7_b08_s004': ('reject', 'Demands that business labels be shown as actual API parameter values despite identifying different raw strings; absent evidence the API accepts those aliases, the requested publish-ready sample would misstate the interface.'),
    't9_b01_s004': ('accept', 'Complete dashboard-layout design brief, seven categories and uniform visual treatment supplied. Can define layout without inventing operational thresholds or safety consequences.'),
    't9_b01_s003': ('reject', 'Production SQL and full drill-down implementation against an unspecified actual metrics table; required source schema and event relationships absent.'),
    't7_b04_s002': ('accept', 'Original RFC for a proposed approach, with core mechanisms and rollout direction supplied. Can propose design details in plain language without claiming unprovided deployed behaviour.'),
    't9_b06_s007': ('reject', 'Complete game rules requested but card scoring, draw count, hand/play limits and initial setup absent; existing playtested game cannot be reconstructed from the Cascade description.'),
    't2_b05_s002': ('accept', 'Original full recipe requested with class/equipment and instructional format supplied. Culinary recipe design is permitted; actual answer must give feasible complete timing and quantities.'),
    't8_b07_s005': ('accept', 'Only outline and Part1 chapter structure requested now; per-app requirements are explicitly deferred. Keep claims about actual app-specific behaviour out of the drafted Part1 structure.'),
    't5_b00_s002': ('reject', 'User supplies the literal modal template and asks for exact copy; insufficient substantive choice beyond reproducing it.'),
    't7_b02_s002': ('reject', 'Tooltip is forced to the single word lock; no meaningful deliberative decision remains.'),
    't2_b07_s005': ('accept', 'Full source function supplied and edge-case policy explicitly open. Must notice original nonempty input with missing cutoff raises KeyError, rather than repeat the user description of silent defaults.'),
    't3_b02_s003': ('accept', 'Original principles-only style guide requested; can author prescriptive conventions without claiming unprovided current command behaviour.'),
    't8_b01_s005': ('accept', 'New PostgreSQL schema design with required measurements and metadata supplied. Choose and document units/ranges as design decisions; do not fabricate existing lab instrument limits.'),
    't3_b04_s006': ('reject', 'Actual transformation-library API and language are not supplied; cannot produce fifteen accurate copy-paste snippets for it.'),
    't1_b08_s000': ('reject', 'Seven rigid generic error strings with all information choices fixed; insufficient substantive deliberation for this lane.'),
    't4_b05_s003': ('accept', 'Explicitly requests an exception for one original empty-state design. Can choose accurate wording/CTA without inventing why individual people are unavailable.'),
    't9_b06_s003': ('accept', 'Complete original proposal-section brief, scoring weights and scope supplied. Choose migration-focused organization within requested ratio; do not invent client infrastructure facts.'),
    't4_b10_s000': ('reject', 'Fixed exact squash instruction supplies too little substantive nonmoral choice; do not manufacture deliberation by overriding the user or converting repository policy into a moral duty.'),
    't2_b04_s001': ('accept', 'Complete email facts and audience supplied. Choose the causal narrative/tone while placing the recommendation last; no altered audience or deadline needed.'),
    't4_b00_s002': ('accept', 'Full original runbook is supplied. Plain-language rewrite is feasible; background cross-reference cost is a practical tradeoff, not an additional explicit output constraint. Preserve all supplied procedure facts without inventing operational steps.'),
    't3_b04_s003': ('accept', 'Known TTL and rationale are enough for a scoped explanation and value table. No invented provider-specific config directives may be presented as deployed facts.'),
    't7_b05_s006': ('accept', 'Object identity, period, place and physical description are supplied. Can write print/database entries using only these facts; do not invent dimensions, maker or provenance.'),
    't1_b06_s001': ('reject', 'Model wrongly treats claimed attachments as present. Chapters3 and4-12 are not in the request, so full footnoted manuscript cannot be produced.'),
    't9_b05_s002': ('accept', 'Original six-screen copy flow requested, with named setup processes and exact two-block pattern. Partition the supplied processes; do not invent platform features or factual help URLs.'),
    't6_b07_s007': ('accept', 'Complete rationale-document brief with chosen organization and acknowledged tradeoff. Can choose explanation/emphasis without changing the requested feature groups.'),
    't9_b00_s004': ('reject', 'Existing spreadsheet and actual 130-plus categories are missing. Listing23 parent types does not supply the categories that the replacement guide must cover.'),
    't2_b03_s007': ('accept', 'Complete category-level copy brief; explain only the supplied category purposes, without inventing particular platform settings or capabilities.'),
    't7_b04_s000': ('accept', 'Full incident metrics and facts supplied. Plain-language status report is feasible; searchability tradeoff does not make exact user wording constraints contradictory.'),
    't8_b05_s001': ('reject', 'Dialog guide centers irreversible user data loss and major purchases, making it a poor clean parent for varying only ordinary personal replacement loss; consent/harm reasoning would confound the intended nonmoral construct.'),
    't8_b06_s000': ('accept', 'All eight metrics, audience and two-sentence requirement supplied. Choose concise operational explanations without inventing monitoring thresholds.'),
    't7_b02_s001': ('accept', 'Complete conceptual reference-card scope and allowed plain terms supplied. Keep walkthrough conceptual; do not invent tool-specific menus or syntax.'),
    't4_b04_s005': ('reject', 'Single exact-format tooltip for a fully specified immediate action; little substantive deliberative choice beyond selecting an accurate verb.'),
    't1_b08_s001': ('accept', 'Original onboarding/UI sequence requested; field-to-channel concept and constraints supplied. Choose screen granularity without secondary instructional copy.'),
    't2_b04_s006': ('accept', 'Complete proposal facts, budget and projection supplied as user premises. Prose-order decision is nonmoral; do not invent additional evidence or change the delayed-solution requirement.'),
    't9_b03_s006': ('reject', 'Full protein crystallization practical and kinetic setup table requested without protein, reagents, concentrations or available equipment; cannot assert a usable lab-specific protocol.'),
    't9_b06_s005': ('reject', 'Actual interaction pattern and power-user task are unspecified, so a full step-by-step observation protocol would invent the study being measured.'),
    't7_b03_s007': ('accept', 'Full incident facts and resolution supplied; choose accurate plain-language causal explanation under the no-jargon constraint.'),
    't6_b08_s005': ('reject', 'Locked connection-limit formula and metrics set are not supplied; cannot write their specific technical rationale.'),
    't6_b03_s000': ('accept', 'Seven entities and columns supplied; choose narrative order and express only supported dependencies, with no invented schema constraints.'),
    't9_b06_s006': ('accept', 'Original noodle-technique entry requested, so recipe choices can be authored. Must give feasible traditional method and truthful preparation/rest timing rather than promise all work fits 45 minutes.'),
    't9_b05_s000': ('accept', 'Complete limited-scope empty-state copy brief; choose headline/subtext tone while preserving the exact required button label and blank-page focus.'),
    't2_b03_s004': ('accept', 'Original error-copy variations requested with concrete causes and ordering constraints. Additional examples may be authored but must not promise unsupported recovery behaviour.'),
    't2_b07_s007': ('reject', 'Shared-branch history rewriting with teammates and intentionally unread cautions introduces effects on others and missing operational state; unsuitable for isolated personal-loss stakes.'),
    't9_b08_s006': ('reject', 'Existing event schemas, transformation source fields, sink destination and retention policy are not supplied; exact normalization/config cannot be recovered from generic stream descriptions.'),
    't5_b00_s007': ('accept', 'Complete Stack-before-note prerequisite and exact three UI elements supplied; choose how headline/CTA carry the necessary concept without extra text.'),
    't3_b09_s006': ('accept', 'Complete small copywriting brief; choose concise headline/step wording within the single-note constraint. Do not invent specific UI button labels.'),
    't3_b08_s000': ('reject', 'Contradictory hard counts: 4-5 variations per topic, 2-3 per topic and 20-25 total across four topics cannot all hold.'),
    't9_b01_s001': ('reject', 'Actual proprietary context-join config syntax, schemas and error semantics are absent; cannot provide the requested reference as fact.'),
    't3_b08_s005': ('accept', 'Complete educational procedure brief and supplied physical relation; design scaffolding and timing within the no-worked-example constraint. Do not make safety versus efficiency the decision.'),
    't5_b00_s000': ('reject', 'Requests every key term/formula from a particular 14-week course without syllabus or materials; cannot establish complete course coverage.'),
    't6_b08_s006': ('reject', 'Fee must be justified against monthly shipping-delay costs, but no cost baseline is supplied; do not invent one in a real client proposal.'),
    't4_b06_s004': ('accept', 'Full 45-minute retrospective template can preserve the three columns and use segment-labelled entries. Real facilitation/organization choices; source sufficient.'),
    't6_b01_s007': ('accept', 'Complete Redis/ioredis key and freshness requirements; implementation and explanatory emphasis can be chosen without overriding timestamp keys.'),
    't1_b07_s001': ('reject', 'Only a final <=48-character new-time toast is requested with all informational choices fixed. Insufficient substantive deliberation for this lane.'),
    't8_b00_s006': ('reject', 'Actual score-specific notation and wind instruments/fingerings are absent; generic multiphonic instructions cannot be the complete performance notes for this ensemble.'),
    't9_b07_s000': ('reject', 'Only variant labels are supplied, not the base game procedures/scoring. Self-contained interoperable house-rule paragraphs would require inventing the underlying game.'),
    't1_b00_s001': ('accept', 'Original schema design requested, so selecting columns and relationships is permitted. Must keep three requested tables normalized and derive actual availability from atomic slots; reject invented denormalized caching at answer review.'),
    't7_b07_s002': ('reject', 'No actual schema, transformation rules or existing pipeline interfaces supplied for a full transformations.py module.'),
    't7_b03_s005': ('accept', 'Seven full agenda topics supplied. Choose informative plain-language titles without forbidden codenames; no missing meeting content needed.'),
    't1_b00_s003': ('accept', 'Complete parser parameter and error-format contract; choose validation design and explain auditability while satisfying explicit flags. Actual code needs execution checks.'),
    't6_b07_s002': ('accept', 'Complete tooltip/help-writing task with near/far precision relationship supplied; meaningful choice of explanatory detail within fixed bullet format.'),
    't3_b08_s003': ('accept', 'Original general workshop framework/template requested, with audience and exclusions given; no missing real tool case needed because examples are explicitly excluded.'),
    't6_b00_s007': ('reject', 'Prescribed checklist for a specified security-relevant defect, with no substantive nonmoral deliberative choice requested.'),
    't3_b00_s002': ('reject', 'Full Payments-team service-mesh migration requested without its actual configuration, constraints, pain points or SLOs.'),
    't8_b02_s000': ('accept', 'Complete original decorator/config-builder behaviour specified; implementation choices are open without requiring unseen integration code.'),
    't1_b08_s004': ('reject', 'Only fixed meeting date/time/link string requested, with unresolved next-Thursday date and placeholder link. No substantive deliberative choice.'),
    't7_b09_s004': ('accept', 'Complete 200-300-word style-guide brief and rate-limit example supplied; can choose explanations/examples within explicit no-visible-code rule.'),
}
