# ABOUTME: The report: renders every Tier A figure and writes the greppable markdown mirror
# ABOUTME: beside it, so every number in a PNG is also readable without opening the PNG.

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Sequence

from . import analysis, plots
from .config import git_sha, timestamp
from .core.store import ResultsStore


def _table(df, columns: Sequence[str], floats: Sequence[str] = (), limit: int = 0) -> str:
    """Render a frame as a markdown table.

    Args:
        df: The frame.
        columns: Columns to include, in order.
        floats: Columns formatted to three decimals.
        limit: Row cap; 0 means all.

    Returns:
        The markdown table, or a placeholder line when there is nothing to show.
    """
    if df is None or df.empty:
        return "_no rows_\n"
    cols = [c for c in columns if c in df.columns]
    rows = df[cols].head(limit) if limit else df[cols]
    header = "| " + " | ".join(cols) + " |"
    rule = "|" + "|".join(["---"] * len(cols)) + "|"
    lines = [header, rule]
    for row in rows.itertuples(index=False):
        cells = []
        for col, value in zip(cols, row):
            if col in floats and isinstance(value, (int, float)):
                cells.append(f"{float(value):.3f}")
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def _ci_table(df, keys: Sequence[str], limit: int = 0) -> str:
    """Render an aggregate frame with its interval collapsed into one readable column."""
    if df is None or df.empty:
        return "_no rows_\n"
    out = df.copy()
    out["95% CI"] = out.apply(lambda r: f"[{r['lo']:.3f}, {r['hi']:.3f}]", axis=1)
    return _table(out, [*keys, "mean", "95% CI", "n"], floats=["mean"], limit=limit)


def build_report(
    source: ResultsStore | Any,
    out_dir: Path | str,
    recipes: Sequence[str] | None = None,
    make_plots: bool = True,
    title: str = "Constitution internalization — Tier A",
) -> dict[str, Any]:
    """Render every Tier A figure and write the markdown mirror and summary JSON.

    Args:
        source: A ResultsStore or a results DataFrame.
        out_dir: Directory to write into.
        recipes: Restrict the whole report to these recipes.
        make_plots: Render figures. False writes tables only.
        title: Report title.

    Returns:
        A mapping of written paths plus the figure index and any warnings.
    """
    df = source.to_frame() if isinstance(source, ResultsStore) else source
    if recipes:
        df = df[df["recipe"].isin(list(recipes))]
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    warnings: list[str] = []
    fingerprints = analysis.check_comparable(df)
    if len(fingerprints) > 1:
        warnings.append(
            f"Rows span {len(fingerprints)} different item sets ({', '.join(fingerprints)}). "
            f"These runs were measured on different items and MUST NOT be compared. Rebuild "
            f"one frozen item set and re-run, or filter to a single itemset_id."
        )
    n_errors = int((df["error"].fillna("") != "").sum())
    if n_errors:
        warnings.append(
            f"{n_errors} of {len(df)} rows carry an error and are excluded from every "
            f"aggregate below (they are not counted as failures)."
        )

    figures = plots.render_all(df, out / "figures", recipes=recipes) if make_plots else {}

    headline = analysis.headline_table(df)
    matrix = analysis.clause_axis_matrix(df)
    retrieval = analysis.retrieval_vs_application(df)
    tension = analysis.compliance_vs_tension(df)
    decay = analysis.ood_decay(df)
    robustness = analysis.robustness_by_wrapper(df)
    robustness_clause = analysis.robustness_delta(df)
    side_effects = analysis.side_effect_panel(df)
    held_out = analysis.held_out_vs_trained(df)

    lines: list[str] = [
        "<!-- ABOUTME: Tier A results mirror - every figure's numbers in greppable form. -->",
        "<!-- ABOUTME: Generated by constieval.report; do not hand-edit. -->",
        "",
        f"# {title}",
        "",
        f"- generated: {timestamp()} UTC",
        f"- git sha: `{git_sha()}`",
        f"- recipes: {', '.join(analysis.recipes(df)) or 'none'}",
        f"- item sets: {', '.join(fingerprints) or 'none'}",
        f"- rows: {len(df)}",
        "",
    ]
    if warnings:
        lines += ["## Warnings", ""] + [f"- **{w}**" for w in warnings] + [""]

    if figures:
        lines += ["## Figures", ""]
        for name in plots.TIER_A_PLOTS:
            path = figures.get(name, "")
            if path.startswith("ERROR:"):
                lines.append(f"- `{name}` — **not rendered**: {path[7:]}")
            elif path:
                lines.append(f"- `{name}` — `{Path(path).relative_to(out)}`")
            else:
                lines.append(f"- `{name}` — no data")
        lines.append("")

    sections = [
        ("Headline — score by recipe and axis", _ci_table(headline, ["recipe", "axis"])),
        (
            "Clause × axis (pooled over recipes)",
            _ci_table(matrix, ["clause_id", "clause_title", "held_out", "axis"]),
        ),
        (
            "Retrieval vs application (per clause)",
            _table(
                retrieval,
                ["recipe", "clause_id", "clause_title", "held_out", "retrieval", "compliance", "n_retrieval", "n_compliance"],
                floats=["retrieval", "compliance"],
            ),
        ),
        (
            "Compliance vs tension recognition (per clause)",
            _table(
                tension,
                ["recipe", "clause_id", "clause_title", "held_out", "compliance", "tension_recognition", "n_compliance", "n_tension_recognition"],
                floats=["compliance", "tension_recognition"],
            ),
        ),
        ("OOD decay (per axis, never pooled)", _ci_table(decay, ["recipe", "ood_axis", "distance", "ood_value"])),
        (
            "Robustness — paired Δ by wrapper",
            _table(
                robustness,
                ["recipe", "pressure", "delta", "lo", "hi", "n"],
                floats=["delta", "lo", "hi"],
            ),
        ),
        (
            "Robustness — paired Δ by clause and wrapper",
            _table(
                robustness_clause,
                ["recipe", "pressure", "clause_id", "axis", "delta", "lo", "hi", "n"],
                floats=["delta", "lo", "hi"],
            ),
        ),
        ("Side-effect panel (native direction)", _ci_table(side_effects, ["recipe", "checkpoint_step", "axis"])),
        (
            "Held-out vs trained clauses (descriptive — see Tier B)",
            _ci_table(held_out, ["recipe", "axis", "held_out"]),
        ),
    ]
    for heading, body in sections:
        lines += [f"## {heading}", "", body, ""]

    md_path = out / "tier_a_results.md"
    md_path.write_text("\n".join(lines))

    summary = {
        "generated_utc": timestamp(),
        "git_sha": git_sha(),
        "recipes": analysis.recipes(df),
        "itemset_ids": fingerprints,
        "n_rows": int(len(df)),
        "n_error_rows": n_errors,
        "warnings": warnings,
        "figures": figures,
        "headline": headline.to_dict("records") if not headline.empty else [],
    }
    summary_path = out / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, default=str))

    return {
        "markdown": str(md_path),
        "summary": str(summary_path),
        "figures": figures,
        "warnings": warnings,
    }
