# ABOUTME: Write a TOP-UP ODCV config for the coherent PAR arm: only the cells still short of 2 non-empty
# ABOUTME: rollouts across its run dirs are kept (everything else excluded), so one short docker pass fills them.
# Run: uv run python scratch/par_coherence/topup_config.py [--target 2] → scratch/par_coherence/odcv_bench_t2_9284_par716coh_topup.yaml
from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from pathlib import Path

import yaml

BASE = Path("scratch/par_coherence/odcv_bench_t2_9284_par716coh_2x65.yaml")
OUT = Path("scratch/par_coherence/odcv_bench_t2_9284_par716coh_topup.yaml")
ROOT = Path("output/odcv_bench/qwen3_6-27b-lora-t2-9284-par716coh-r64-dynbatch")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", type=int, default=2)
    ap.add_argument(
        "--base_url",
        default="https://mqg4957z6t2f2u-8000.proxy.runpod.net/v1",
        help="endpoint the containers call; the RunPod HTTPS proxy of the CURRENT serve pod "
        "(the SSH tunnel kept resetting on 2026-08-28). Re-running this script regenerates the "
        "yaml, so the URL must live here, not in a hand edit.",
    )
    args = ap.parse_args()
    cfg = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    universe: set[str] = set()
    have: Counter = Counter()
    for run in sorted(
        p for p in ROOT.iterdir() if p.is_dir() and not p.name.startswith("combined")
    ):
        man = run / "rollout_manifest.json"
        if man.is_file():
            m = json.loads(man.read_text(encoding="utf-8"))
            rows = m if isinstance(m, list) else (m.get("scenarios") or m.get("results") or [])
            for row in rows:
                if isinstance(row, dict) and "variant" in row and "scenario" in row:
                    universe.add(f"{row['variant']}/{row['scenario']}")
        # cells that only ever produced a directory (empty/partial pass) still belong to the universe
        for p in run.glob("agent_logs/*/experiments/*"):
            if p.is_dir():
                universe.add(f"{p.parts[-3].rsplit('-', 1)[-1]}/{p.name}")
        for p in run.glob("agent_logs/*/experiments/*/messages_record.txt"):
            if os.path.getsize(p) > 0:
                cond = p.parts[-4].rsplit("-", 1)[-1]
                have[f"{cond}/{p.parts[-2]}"] += 1
    universe -= set(cfg["exclude_scenarios"])
    short = sorted(c for c in universe if have[c] < args.target)
    keep_out = sorted(set(cfg["exclude_scenarios"]) | (universe - set(short)))
    top = dict(cfg)
    top["expected_cells"] = len(short)
    top["base_url"] = args.base_url
    top["exclude_scenarios"] = keep_out
    header = (
        "# ABOUTME: TOP-UP pass for the coherent PAR-716 arm: only the cells that ended short of "
        f"{args.target} non-empty rollouts\n# ABOUTME: after its passes (generated by scratch/par_coherence/topup_config.py; everything else excluded).\n"
        "# Run: bash scratch/par_b/odcv_local_run.sh <ip> <port> 1 12 scratch/par_coherence/odcv_bench_t2_9284_par716coh_topup.yaml "
        "LASR-Callum/2026-08-28-odcv-par716coh-eval output/odcv_par716coh_topup_state\n"
    )
    OUT.write_text(header + yaml.safe_dump(top, sort_keys=False), encoding="utf-8")
    print(
        f"universe {len(universe)} cells; short of {args.target}: {len(short)} -> {OUT}"
    )
    for c in short:
        print(f"  {c}: {have[c]}")


if __name__ == "__main__":
    main()
